export const FETCHED_DETAILS = "FETCHED_DETAILS";
export const EDITED_TITLE = "EDITED_TITLE";
export const EDITED_SUBTITLE = "CHANGED_SUBTITLE";
export const EDITED_SEARCH_BAR = "EDITED_SEARCH_BAR";
export const ADDED_APPLICATION = "ADDED_APPLICATION";
export const REMOVEED_APPLICATION = "REMOVEED_APPLICATION";
export const EDITED_APPLICATION = "EDITED_APPLICATION";
